name: SMSML CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: yourdockerhubusername/smsml-model:latest

jobs:
  lint-build-train-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy joblib fastapi uvicorn prometheus_client

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 MLProject/ --max-line-length=120 --ignore=E203,W503 --exit-zero

    - name: Run training script
      working-directory: MLProject
      run: python modelling.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          MLProject/model/

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME

    # (Opsional) Deploy ke server/container jika diperlukan
    # - name: Deploy to server
    #   run: |
    #     ssh user@your-server 'docker pull $IMAGE_NAME && docker run -d -p 8000:8000 $IMAGE_NAME'
